model:
  - num_layers: 1
  - save_dir: output/robospatial_configuration/probe/Spatial457/l12

training:
  - sklearn_C: 100.0
  - sklearn_solver: lbfgs
  - sklearn_max_iter: 1000
  - loss: CrossEntropyLoss

test:
  - loss: CrossEntropyLoss

data:
  - input_db: output/robospatial_configuration/Molmo-7B-O-0924-Spatial457.db
  - db_name: tensors
  - input_layer: model.transformer.blocks.12.ff_norm