architecture: molmo
model_path: allenai/Molmo-7B-O-0924
model:
  - torch_dtype: auto
forward:
  - max_new_tokens: 1
  - stop_strings: <|endoftext|>
dataset:
  - local_dataset_path: /data/shared/Qwen/vlm-lens-mod/data/robospatial/configuration
output_db: output/Molmo-7B-O-0924.db
pooling_method: mean
modules:
  - model.transformer.blocks.*.ff_norm
